name: Update Github
on:
  push:
  branches:
      - master
  paths:
      - 'packages/auth/*.xml'

defaults:
  run:
    working-directory: maven/latest

jobs:
  build:
    name: "Update Github"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        name: Checkout Code
        
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id : ${{ secrets.AWS_KEY }}
          aws-secret-access-key : ${{ secrets.AWS_SECRET }}
          aws-region: "us-east-1"

      - uses: shinyinc/action-aws-cli@v1.2
      - run: aws s3 sync dist s3://${{ secrets.AWS_S3_BUCKET_NAME }}/maven/latest
        env: 
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: 'ap-south-1
